version: '3'

services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx01
    ports:
      - "80:8000"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/certs:/etc/nginx/ssl
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
    restart: unless-stopped

  # Redis - result backend
  redis:
    image: redis:3.2.11-alpine
    hostname: redis
    restart: unless-stopped

  # RabbitMQ - queue
  rabbit:
    hostname: rabbit:3.6.15-alpine
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"  # here, we can access rabbitmq management plugin
    restart: unless-stopped

  db:
    image: postgres:10.3-alpine
    volumes:
        - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    container_name: dj01
    hostname: web
    command: bash -c "
        mkdir -p logs
        && python manage.py migrate
        && python manage.py collectstatic --noinput
        && gunicorn dflk.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/code
      - ./static:/static
    expose:
      - "8000"
      - "443"
    depends_on:
      - db
    links:
      - rabbit
      - redis
    restart: unless-stopped

  # Celery worker
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A dflk worker -l info
    volumes:
      - .:/code
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
    restart: unless-stopped

  # Celery beat
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "
      rm -rf celerybeat.pid celerybeat-schedule
      && celery -A dflk beat -l info"
    volumes:
      - .:/code
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
    restart: unless-stopped

volumes:
    postgres:
