# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='allowed_users',
        ),
        migrations.RemoveField(
            model_name='project',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='project',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
