# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0002_auto_20180311_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPObject',
            new_name='HistoricalProjectObject',
        ),
        migrations.RenameModel(
            old_name='PObject',
            new_name='ProjectObject',
        ),
        migrations.AlterModelOptions(
            name='historicalprojectobject',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project object'},
        ),
    ]
