# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0003_auto_20180311_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='folder_id',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalprojectobject',
            name='folder_id',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='folder_id',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='folder_id',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
        ),
    ]
