# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0005_auto_20180311_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='folder_id',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='ID Папки'),
        ),
        migrations.AlterField(
            model_name='historicalprojectobject',
            name='folder_id',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='ID папки'),
        ),
        migrations.AlterField(
            model_name='historicalprojectobject',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=120, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Допущенные пользователи'),
        ),
        migrations.AlterField(
            model_name='project',
            name='folder_id',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True, verbose_name='ID Папки'),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='folder_id',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True, verbose_name='ID папки'),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=120, unique=True, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parea.Project', verbose_name='Проект'),
        ),
    ]
