# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0006_auto_20180311_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectobject',
            name='main_file',
            field=models.CharField(choices=[('1', 'id1'), ('2', 'id2'), ('3', 'id3'), ('4', 'id4')], db_index=True, default='', max_length=120, verbose_name='Основная таблица'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='main_file',
            field=models.CharField(choices=[('1', 'id1'), ('2', 'id2'), ('3', 'id3'), ('4', 'id4')], db_index=True, default='', max_length=120, unique=True, verbose_name='Основная таблица'),
        ),
    ]
