# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0009_auto_20180312_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectobject',
            name='main_file',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Основная таблица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='main_file',
            field=models.CharField(blank=True, db_index=True, default='some', max_length=50, unique=True, verbose_name='Основная таблица'),
            preserve_default=False,
        ),
    ]
