# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0010_auto_20180312_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectobject',
            name='main_file',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, verbose_name='Основная таблица'),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='main_file',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True, verbose_name='Основная таблица'),
        ),
    ]
