# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0012_systemvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemvalues',
            name='changes_token',
            field=models.CharField(db_index=True, default='', max_length=20, unique=True, verbose_name='Changes Token'),
        ),
    ]
