# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0016_auto_20180314_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectobject',
            name='list1_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, verbose_name='ID 1 листа'),
        ),
        migrations.AddField(
            model_name='historicalprojectobject',
            name='list2_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, verbose_name='ID 2 листа'),
        ),
        migrations.AddField(
            model_name='historicalprojectobject',
            name='list3_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, verbose_name='ID 3 листа'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='list1_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True, verbose_name='ID 1 листа'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='list2_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True, verbose_name='ID 2 листа'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='list3_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True, verbose_name='ID 3 листа'),
        ),
    ]
