# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0017_auto_20180314_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemvalues',
            name='hidden_folder',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True, verbose_name='Скрытая папка'),
        ),
        migrations.AddField(
            model_name='systemvalues',
            name='parent_folder',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True, verbose_name='Основная папка для проектов'),
        ),
    ]
