# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0021_auto_20180323_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectobject',
            name='synced',
            field=models.BooleanField(default=False, verbose_name='Синхронизировано'),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='synced',
            field=models.BooleanField(default=False, verbose_name='Синхронизировано'),
        ),
    ]
