# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0022_auto_20180323_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectobject',
            name='sync_task_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, verbose_name='ID задачи синхронизации'),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='sync_task_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='ID задачи синхронизации'),
        ),
    ]
