# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 12:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0023_auto_20180323_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='editor_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Допущены к Google Drive'), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='project',
            name='editor_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Допущены к Google Drive'), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='history_type',
            field=models.CharField(choices=[('+', 'Создан'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalprojectobject',
            name='files_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'graphs': []}),
        ),
        migrations.AlterField(
            model_name='historicalprojectobject',
            name='history_type',
            field=models.CharField(choices=[('+', 'Создан'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Допущены по API'),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='files_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'graphs': []}),
        ),
    ]
