# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 12:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0025_auto_20180402_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='editor_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None, verbose_name='Допущены к Google Drive'),
        ),
        migrations.AlterField(
            model_name='project',
            name='editor_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None, verbose_name='Допущены к Google Drive'),
        ),
    ]
