# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 15:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0026_auto_20180402_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='files_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'documents': [], 'information': [], 'talks': []}, verbose_name='Структура файлов'),
        ),
        migrations.AddField(
            model_name='project',
            name='files_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'documents': [], 'information': [], 'talks': []}, verbose_name='Структура файлов'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalprojectobject',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
    ]
