# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parea', '0027_auto_20180404_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=120, unique=True, verbose_name='ФИО')),
                ('company', models.CharField(db_index=True, default='', max_length=120, unique=True, verbose_name='Компания')),
                ('position', models.CharField(db_index=True, default='', max_length=120, unique=True, verbose_name='Должность')),
                ('phone', models.CharField(db_index=True, default='', max_length=120, unique=True, verbose_name='Телефон')),
                ('email', models.CharField(db_index=True, default='', max_length=120, unique=True, verbose_name='Email')),
                ('projects', models.ManyToManyField(blank=True, to='parea.Project', verbose_name='Проекты')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=120, verbose_name='ФИО')),
                ('company', models.CharField(db_index=True, default='', max_length=120, verbose_name='Компания')),
                ('position', models.CharField(db_index=True, default='', max_length=120, verbose_name='Должность')),
                ('phone', models.CharField(db_index=True, default='', max_length=120, verbose_name='Телефон')),
                ('email', models.CharField(db_index=True, default='', max_length=120, verbose_name='Email')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical contact',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
