# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parea', '0028_contact_historicalcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(default='', max_length=120, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=120, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(default='', max_length=120, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='company',
            field=models.CharField(default='', max_length=120, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=models.CharField(default='', max_length=120, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='position',
            field=models.CharField(default='', max_length=120, verbose_name='Должность'),
        ),
    ]
