# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 20:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parea', '0029_auto_20180405_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, verbose_name='Название трансляции')),
                ('iframe', models.TextField(default='', verbose_name='Код для вставки')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил контакт'),
        ),
        migrations.AddField(
            model_name='contact',
            name='document_link',
            field=models.CharField(default='', max_length=300, verbose_name='Ссылка на утверждающий документ'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='document_link',
            field=models.CharField(default='', max_length=300, verbose_name='Ссылка на утверждающий документ'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='main_photo',
            field=models.TextField(default='', max_length=100, verbose_name='Основное фото проекта'),
        ),
        migrations.AddField(
            model_name='historicalprojectobject',
            name='photo_files_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Структура файлов с фото'),
        ),
        migrations.AddField(
            model_name='historicalprojectobject',
            name='photo_folder_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, verbose_name='ID папки с фотографиями'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_photo',
            field=models.ImageField(default='', upload_to='parea/img/projects', verbose_name='Основное фото проекта'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='photo_files_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Структура файлов с фото'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='photo_folder_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='ID папки с фотографиями'),
        ),
        migrations.AlterField(
            model_name='historicalprojectobject',
            name='files_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'documents': [], 'graphs': [], 'information': []}),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='files_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'documents': [], 'graphs': [], 'information': []}),
        ),
        migrations.AddField(
            model_name='videoframe',
            name='prj_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parea.ProjectObject', verbose_name='Проект'),
        ),
    ]
